apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    env: prod
    app: main
spec:
  containers:
  - name: container-nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: container-api
    image: tomcat:8.5.38
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
