apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kuber-app
  template:
    metadata:
      labels:
        app: kuber-app
    spec:
      containers:
      - name: app
        image: bokovets/kuber:v1.0
        resources:
          # limits:
        ports:
        - name: http
          containerPort: 8000
