apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymend-bokovets-kuber-unhealthy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bokovets-kuber-unhealthy
  template:
    metadata:
      labels:
        app: bokovets-kuber-unhealthy
    spec:
      containers:
      - name: pod-bokovets-kuber-unhealthy
        image: bakavets/kuber:v1.0-unhealthy
        resources:
        ports:
        - name: http
          containerPort: 8000
        readinessProbe: #готовности
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe: #работоспособности
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-bokovets-kuber-unhealthy
spec:
  type: NodePort
  selector: 
    app: bokovets-kuber-unhealthy
  ports:
  - port: 80
    targetPort: http
