apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    name: podService
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: http 
        containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: podService
  ports:
  - port: 80
    targetPort: http
