apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    app: selecton # совпадает (1)
  template:
    metadata:
      name: myapp
      labels:
        app: selecton # совпадает (1)
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
