apiVersion: v1
kind: PersistentVolume
metadata:
  name: runner-pv-config
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: runner-storage-config
  local:
    path: /var/lib/gitlab/runner/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube # kubectl get nodes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-pvc-config
spec:
  storageClassName: runner-storage-config
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce