apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-deployment
spec:
  selector:
    matchLabels:
      app: runner-deployment-pod
  template:
    metadata:
      labels:
        app: runner-deployment-pod
    spec:
      containers:
      - name: runner-deployment-container
        image: gitlab/gitlab-runner:alpine
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
          - name: runner-pvc-config
            mountPath: /etc/gitlab-runner
          - name: docker-sock-volume
            mountPath: /var/run/docker.sock
            readOnly: true
      volumes:
        - name: runner-pvc-config
          persistentVolumeClaim:
            claimName: runner-pvc-config
        - name: docker-sock-volume
          hostPath:
            path: /var/run/docker.sock
            type: File