apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pg
  namespace: prod
spec:
  storageClassName: pg-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
