apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: nginx
        resources:
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /test-dir
            name: test-volume

      volumes:
        - name: test-volume
          emptyDir: {}
