apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-config
spec:
  storageClassName: gitlab-storage-config
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

